version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myP@ssw0rd

  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py createsu &&
      gunicorn --bind 0.0.0.0:8000 blog_django.wsgi:application
      "
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_NAME=blogdb
      - DATABASE_USER=dbadminuser
      - DATABASE_PASSWORD=myP@ssw0rd
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ALLOWED_HOSTS=20.193.158.152
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=Admin@123

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
      - ./uploads:/app/uploads
    depends_on:
      - web

volumes:
  postgres_data:

